{% set name = "featureclass" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/featureclass-{{ version }}.tar.gz
  sha256: ef8f586622aae156eda6d79d86187cac310ffe3d5c0cfbbb12ef3d9ae1ae7bc5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry >=0.12
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - featureclass
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Itayazolay/featureclass
  summary: Feature engineering library that helps you keep track of feature dependencies, documentation and schema
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
